### ISSUE TITLE
add docs for contirbuting

### ISSUE THREAD

**Issue by foxreymann** [newsuk/AyeSpy#105]
I want to make a PR, made my commits, and then it is blocked as it requests semantic commits. and now I have to amend my commit, mess. please add docs on how to contribute

**Comment by L0wry** [comment]
Conventional Commits.
Testing.
PR description.

**Comment by foxreymann** [comment]
thx, but more like to a README.md not here:)

**Comment by kaliabadi** [comment]
https://github.com/newsuk/AyeSpy/pull/109
