### ISSUE TITLE
Test various Browsers

### ISSUE THREAD

**Issue by tuan91** [newsuk/AyeSpy#156]
Hi, is it possible to test various browsers? Like Firefox, Safari ...
If so, how can I do that?
Thank you!

**Comment by L0wry** [comment]
Hi @tuan91
Currently, ayespy supports both chrome and firefox browsers running on a selenium grid. I have just noticed that this is not very clear in the README and I will address that now.

To run either chrome or firefox do this from the cli
`ayespy snap --browser chrome --config config.json`
`ayespy snap --browser firefox --config config.json`

Ayespy could be extended fairly easily to support Safar, but you would need to add safari browsers to your selenium grid. 
Apple restricts safari to one automation session per machine and can't run inside a docker container which is a real pain and as such, we decided it didn't provide enough value to implement.

**Comment by L0wry** [comment]
closing this issue as the read me has now been updated
