### ISSUE TITLE
Handle promise rejection when selenium Url is incorrect

### ISSUE THREAD

**Issue by OanaPasnicu** [newsuk/AyeSpy#159]
Running:
ayespy snap --config ayespy-config.json --browser firefox

Tried multiple versions of node, including v9.11.2 (mentioned in the e2e Test Dockerfile)

Error:
at parseHttpResponse (/.nvm/versions/node/v9.11.2/lib/node_modules/aye-spy/node_modules/selenium-webdriver/lib/http.js:557:11)
    at Executor.execute (/.nvm/versions/node/v9.11.2/lib/node_modules/aye-spy/node_modules/selenium-webdriver/lib/http.js:468:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
(node:614) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejec)

I think the problem happens here:
https://github.com/newsuk/AyeSpy/blob/9b6760e1cfe943e146bc765d363f2985aafca365/src/getScreenshots.js#L60

**Comment by OanaPasnicu** [comment]
The AyeSpy-config.json file:

`{
    "gridUrl": "http://localhost:4444/",
    "baseline": "./baseline",
    "latest": "./latest",
    "generatedDiffs": "./generatedDiffs",
    "report": "./report",
    "scenarios": [
        {
            "url": "removed the actual link",
            "label": "gh",
           "removeSelectors": ["#cfg-cnt"],
            "viewports": [
                {
                    "height": 900,
                    "width": 800,
                    "label": "large"
                }
            ]
        }
    ]
}`

**Comment by L0wry** [comment]
Hi @OanaPasnicu,

We will investigate this! 
thank you for reporting!

**Comment by L0wry** [comment]
@OanaPasnicu managed to replicate with your config 💯

**Comment by OanaPasnicu** [comment]
@L0wry thanks for the suggestion! 

Initially, I got another error after replacing the gridUrl and no image generated.
<img width="1657" alt="screen shot 2019-02-01 at 07 44 13" src="https://user-images.githubusercontent.com/5557667/52110113-85982000-25f7-11e9-94e8-f336045b3fcf.png">

I have run the command again and this time it worked fine, with the screenshot generated.

**Comment by L0wry** [comment]
This to me looks like an error from selenium itself which suggests there is an alert box on the page under test.

You should be able to handle alert boxes by using the `onReadyScript ` and use the browser object to dismiss the alert before taking the screenshot.

**Comment by L0wry** [comment]
#168  will clean this up
