### ISSUE TITLE
Images not loaded in AyeSpy Comparison Report

### ISSUE THREAD

**Issue by Xin00163** [newsuk/AyeSpy#50]
<img width="1680" alt="screen shot 2018-07-02 at 16 41 20" src="https://user-images.githubusercontent.com/12214841/42173464-fc3aea50-7e16-11e8-9f25-90cc2a4a861e.png">

**Comment by L0wry** [comment]
is this locally running or using s3?

need some more info to debug this @Xin00163

**Comment by L0wry** [comment]
this was due to the s3 bucket policy - closing
