### ISSUE TITLE
Automatically create an AyeSpy folder 

### ISSUE THREAD

**Issue by Xin00163** [newsuk/AyeSpy#51]
It's better to create an AyeSpy folder and store the latest, baseline, generateDiffs and report folder inside it. Otherwise, it looks a bit confusing. See below:
<img width="293" alt="screen shot 2018-07-02 at 16 49 03" src="https://user-images.githubusercontent.com/12214841/42173733-f11f64d8-7e17-11e8-9ed7-36ab2e993243.png">

**Comment by L0wry** [comment]
this is already handled, you specify the folders in your config. The folders will be created on running @Xin00163
