### ISSUE TITLE
Snapshot of page components

### ISSUE THREAD

**Issue by sonmi451** [newsuk/AyeSpy#65]
Is it possible get snaps of and to run checks against a component of the page layout, rather than the whole page?

**Comment by L0wry** [comment]
Hey @sonmi451 

This is something that we thought about doing and decided it wouldn't be a use case for The Times at the moment. However, I can see value for others.

I think there are two potential ways of solving this. One would be to get the elements co-ordinates along with its height and width and then crop the screenshot.

The other, which I think would be my preferred solution is run client side js to hide everything apart from one element then screenshot.

In the meantime, it might be possible to achieve what you are after using the hide selectors.

I'll get a ticket onto the backlog and it will get picked up once someone has some slack, or feel free to tackle it yourself.

Hope this helps!

**Comment by sonmi451** [comment]
Thanks! I'll give it a shot to see if I get anything good working

**Comment by kaliabadi** [comment]
@sonmi451 we have just added this feature! 

If you give it a go let us know how you find it :)
