### ISSUE TITLE
Enhancment: Paint over and block fill dynamic elements

### ISSUE THREAD

**Issue by lukasr22** [newsuk/AyeSpy#91]
Enhancment for instead of removing object can be some mocking of selectors. Selector can be replace with default box image and the whole context of page will be still as it is. (good for animated gifs or videos to cover everytime different pictures).

**Comment by L0wry** [comment]
Whoever does this make sure it's tagged as a breaking change

**Comment by L0wry** [comment]
something to consider here is some elements such as ads render at a variable height on each paint.
this could mean that this would not work for some cases and we would have to use the remove still.

with this in mind, we should facilitate both removing elements and blocking them.

Also, it might be easier to do the blocking of elements post snapshot. 
if we have the x,y coordinates of each of the snaps we can paint over the image

**Comment by L0wry** [comment]
done some more research. 
This could be possible using jimp but will be extremely expensive computationally.
it looks like we can do this in the dom using 

`opacity: 0` 

in css
