### ISSUE TITLE
Ability to run scenarios based on a filter

### ISSUE THREAD

**Issue by mdcruz** [newsuk/AyeSpy#92]
Add support to run tests on a given filter so specific scenarios can be run without running the full suite

**Comment by L0wry** [comment]
been wanting to do this for ages

was thinking it should be a cli command passed through?
I think I would only want to run a scenario one at a time. If we wanted to ignore lots then there should be a flag in the scenario?

**Comment by mdcruz** [comment]
Yes it will be via command line so something like `ayespy snap --filter label_name` I think we should only run one scenario at a time.

**Comment by L0wry** [comment]
`--run` ? ;)

**Comment by kaliabadi** [comment]
Completed in https://github.com/newsuk/AyeSpy/issues/92
