### ISSUE TITLE
browser.wait return an error

### ISSUE THREAD

**Issue by PatMurray86** [newsuk/AyeSpy#97]
Using 
`await browser.wait(until.elementIsVisible(browser.findElement(By.id('ELEMENTID'))), 10000);`
now returns 
`ERR! [snapshotter] : ❌  Unable to run script due to: TypeError: Wait condition must be a promise-like object, function, or a Condition object`

This command was working in the past

**Comment by L0wry** [comment]
This looks like more of an issue around seleniumjs than ayespy, ayespy will only run the script that it is given
